# Site details
title: "SMB Admin"
logo: "/static/images/logo-ubuntu-white.svg"

# Path to the assets (${docRoot}/static)
docRootAdmin: "."
docRootUser: "."

# Network port for the services
portAdmin: "8000"
portUser: "8001"
