name: smb-admin
version: 0.1
summary: SMB Solution Admin Service
description: Admin service for the SMB Solution.
grade: stable
confinement: strict

apps:
    smb-admin:
      command: bin/run-service
      daemon: simple
      plugs:
        - network
        - network-bind
        - system-observe
parts:
    service:
        plugin: go
        source: git://github.com/ubuntu-core/smb-admin
        go-importpath: github.com/ubuntu-core/smb-admin
    assets:
        source: static
        plugin: dump
        organize:
            "*": static/
    scripts:
        source: bin
        plugin: dump
        organize:
            "run-service": bin/run-service
